version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-next
    environment:
      - MONGODB_SERVER=mongodb://mongodb:27017/node-boilerplate
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - node-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge